import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Charting Library Spike <a href="https://upstartnetwork.atlassian.net/browse/REL-9508">REL-9508</a>
        </h1>
        <div className={styles.grid}>
          <a href="#" className={styles.card} onClick={() => router.push('/apex')}>
            <h2>APEX Charts &rarr;</h2>
            <p>Modern & Interactive Open-source Charts</p>
          </a>
          <a href="#" className={styles.card} onClick={() => router.push('/chartjs')}>
            <h2>ChartJS &rarr;</h2>
            <p>Simple yet flexible JavaScript charting for designers & developers</p>
          </a>
        </div>
      </main>
    </div>
  )
}
